---
title: Deep Learning Notes
---

# Questions

The Questions section is there so we can track *work-in-progress* questions. Any question we might have is to be put here.
As we work through the material, answered questions become part of Notes section.

## Normalization vs Standardization vs Scaling down

Normalization 

$$\dfrac{X - X_{min}}{X_{max} - X_{min}}$$

Standardization 

$$\dfrac{X - \bar{X}}{\sigma_X}$$

Scaling down 

$$\dfrac{X}{X_{max}}$$

When to use each? 

[*Next Step*]{.underline}: Batch normalization: when to use and key benefits. Batch normalization vs dataset normalization. Is batch standardization even a thing?

## Our API vs Torch

Torch seems to be learning significantly faster, but it is a lot more volatile. Our loss curve is very smooth, but torch's is wiggly (see mnist.ipynb). 
Our implementation may be missing something.

## Network Depth vs Thickness

How does depth vs thickness affect the performance? What is better: 1 layer with 100 neurons or 10 layers 10 neurons each?

## "No He" with momentum seems to break

See figure in Initialization section. Weight initialization with $N(0, 1)$ behaves very oddly with enabled momentum. Why is that?

# Notes

The Notes section contains resolved/answered questions as well as notes and deeper explanations of the material from the books.

## Initialization

Weights to transform 
$$H_{i} \xrightarrow{W_{|H_i| \times |H_o|}} H_{o}$$

For networks with ReLU activation, initialization is best done by drawing from Gaussian distribution of shape:
$$N{\left( \mu=0, \sigma^2 = {2}/{|H_i|} \right)}$$

this initialization method is called *He initialization*. It prevents "dying ReLU" and vanishing gradients, allowing deeper network training.

Noticeable benefit

```{python}
# | echo: false
# | output: true

import pandas as pd

import holoviews as hv

hv.extension("plotly")

df = pd.read_feather("../mini_dl_framework/he_init_hists.arrow")

no_momentum = (hv.Curve(df[["hist_no_he_no_momentum"]]) * hv.Curve(df[["hist_he_no_momentum"]])).opts(
    xlabel="Epoch", ylabel="Loss", title="No momentum"
)
with_momentum = (hv.Curve(df[["hist_no_he"]]) * hv.Curve(df[["hist_he"]])).opts(
    xlabel="Epoch", ylabel="Loss", title="With momentum"
)

no_momentum + with_momentum
```

## Addressing Overflow

When doing computations, overflows may occur (e.g. SoftMax overflow as $e^x$ explodes, hidden layer overflow in large matrix multiplications)

### Addressing Overflow in SoftMax

To address overflow in SoftMax, we can subtract maximum element from the input vector:
$$ X' = X - X_{max} $$

and then apply SoftMax:
$$ \mbox{SoftMax}(X) = \mbox{SoftMax}(X') = \dfrac{e^{X'}}{\sum{e^{X'}}} $$

Validity of this can be verified by running the following code snippet:

```{python}
import numpy as np

def softmax(X):
  return np.exp(X) / np.sum(np.exp(X))

```

```{python}
#| echo: true
#| output: true

X1 = np.array([1, 2, 3, 4, 5])
X2 = X1 - np.max(X1)

```

```{python}
#| echo: false
#| output: true

print(f"{X1=}\n{X2=}")

```

```{python}
#| echo: true
#| output: true

S1 = softmax(X1)
S2 = softmax(X2)

```

```{python}
#| echo: false
#| output: true
print(f"{S1=}\n{S2=}")
```

### Addressing overflow in ReLU

Networks with ReLU activation are more resistent to underflows than overflows due to ReLU clipping output on the bottom, but not at the top.
Overflow at the top is addressed by setting an upper bound (usually 1).

```{python}
#| echo: true
#| output: true

def ReLU(X, clip=1):
  relu = np.maximum(X, 0)
  return np.minimum(relu, clip)
```

## Forward-and-Backpropagation in Batches

In literature, neural nets are commonly depicted as 

with matrix multiplications as follows:

$$X_{1 \times |X|}W^0_{|X| \times |H^1|} + B_{1 \times |H^1|} = H^1_{1 \times |H^1|}$$

$$H^1_{1 \times |H^1|}W^1_{|H^1| \times |H^2|} + B_{1 \times |H^2|} = H^2_{1 \times |H^2|}$$

$$ \dots $$

$$H^{n-1}_{1 \times |H^{n-1}|}W^{n-1}_{|H^{n-1}| \times |H^n|} + B_{1 \times |H^n|} = H^n_{1 \times |H^n|}$$

$$H^n_{1 \times |H^n|}W^n_{|H^{n}| \times |Y|} + B_{1 \times |Y|} = \hat{Y}_{1 \times |Y|}$$


Batch-processing

In forward-propagation, batch size $b$ nicely replaces 1 in matrix operations. 1-d input becomes $b$-d input and matrix multiplications are
as follows:

$$X_{b \times |X|}W^0_{|X| \times |H^1|} + B_{1 \times |H^1|} = H^1_{b \times |H^1|}$$

$$H^1_{b \times |H^1|}W^1_{|H^1| \times |H^2|} + B_{1 \times |H^2|} = H^2_{b \times |H^2|}$$

$$ \dots $$

$$H^{n-1}_{b \times |H^{n-1}|}W^{n-1}_{|H^{n-1}| \times |H^n|} + B_{1 \times |H^n|} = H^n_{b \times |H^n|}$$

$$H^n_{b \times |H^n|}W^n_{|H^{n}| \times |Y|} + B_{1 \times |Y|} = \hat{Y}_{b \times |Y|}$$

Note that bias $B^i_{1 \times |H^{i+1}|}$ is broadcasted along the dimension of the batch indices (1st dimension).

## Loss Functions

### Cross-Entropy Loss
